### ISSUE TITLE
How to : test locahost page on phone

### ISSUE THREAD

**Issue by R4ph3rd** [AtelierNum/templates#11]
I used to test my p5js sketches or just web app on my phone, and simply connect my phone to the right port of my computer to access to the served page. I have a js script to get the right url to paste on my phone's browser already in my pocket.
Could be nice to have a tuto to explain how to do it in few lines, isn't it ?

I can handle it quickly.

I don't know where to store it, in another tech folder called 'js' or somewhere else ?

**Comment by zhakkarn** [comment]
Could you make a branch on a repo so I can look at it and give you a proper answer?

**Comment by b2renger** [comment]
@R4ph3rd , @zhakk-harn gave you a feedback on you PR. 
But what could be really cool is display a qr code to scan with your phone :)

**Comment by R4ph3rd** [comment]
Actually, as long it is only a util, and not integrated to a server, we can't use a QR Code because it does not include the localhost port of the server ; its objective is only to get the IP adress of the desktop.
But it would be great indeed to add it with a QR Code in server examples (either with something in the [terminal](https://www.npmjs.com/package/qrcode-terminal), either opening it in the default browser window.

**Comment by zhakk-harn** [comment]
transfered in this template idea #22
