### ISSUE TITLE
turn p5.js/hello-world into a "sketchbook" template

### ISSUE THREAD

**Issue by zhakk-harn** [AtelierNum/templates#7]
this template will have an index.html with a grid showing all the sketches contained inside a "sketches" folder. Ideally the UX I aim at is to have the students starting with this template and create a new file in the "sketches" folder anytime they need a blank slate.
 
This is nice because it will nudge them into having all their stuff tidy and also show them how much they've grown from start to finish when they'll look back at the index.html

**Comment by zhakkarn** [comment]
could I add a button in the index.html to scaffold a new sketch then navigate to it?
(like the good ol' slush days)

**Comment by zhakkarn** [comment]
It might also make a really decent base for a "100 days of creative code" challenge

**Comment by zhakkarn** [comment]
Additional Feature documentation : Have a page which gives a slide show to recap the progression, possibly with a timer going to the next sketch every X seconds or a slider, or Previous/Next buttons, IDK

**Comment by zhakkarn** [comment]
You may want to unsubscribe from this 

Additional Feature documentation : given that we can use the root directory in any branch, make the build function leave the project in a "push to deploy" state

**Comment by zhakk-harn** [comment]
moved to another repo to be its own thing
